<?php

namespace App\Services\Media;

use Illuminate\Http\Request;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\Log;
use Throwable;

/**
 * Persists browser-generated image derivatives without requiring GD/Imagick.
 *
 * Originals remain the canonical private files. Derivatives are optional: an
 * older browser or a failed conversion must never make the original upload
 * fail. Invalid derivatives are discarded and marked pending so they can be
 * regenerated by the manual maintenance workflow.
 */
class ClientImageVariantStore
{
    /** @var array<string, true> */
    private array $createdDerivativePaths = [];

    private const WEB_MAX_BYTES = 2 * 1024 * 1024;

    private const THUMBNAIL_MAX_BYTES = 512 * 1024;

    private const WEB_MAX_SIDE = 1920;

    private const THUMBNAIL_MAX_SIDE = 480;

    private const ALLOWED_MIME_TYPES = [
        'image/jpeg' => 'jpg',
        'image/png' => 'png',
        'image/webp' => 'webp',
    ];

    /**
     * @param  array<int, array<string, mixed>>  $originals
     * @return array<int, array<string, mixed>>
     */
    public function attachFromRequest(
        array $originals,
        Request $request,
        string $webField,
        string $thumbnailField,
        string $relativeDirectory,
    ): array {
        $webFiles = $this->uploadedFiles($request->file($webField, []));
        $thumbnailFiles = $this->uploadedFiles($request->file($thumbnailField, []));
        if (count($webFiles) !== count($originals) || count($thumbnailFiles) !== count($originals)) {
            // Partial arrays cannot be paired safely by index. Keep every
            // original and let manual maintenance regenerate all derivatives.
            $webFiles = [];
            $thumbnailFiles = [];
        }

        foreach ($originals as $index => $original) {
            $originalPath = $this->sanitizeRelativePath((string) ($original['path'] ?? ''));
            if ($originalPath === '') {
                continue;
            }

            $metadata = $this->originalMetadata($originalPath);
            $webPath = $this->storeDerivative(
                $webFiles[$index] ?? null,
                $relativeDirectory.'/web',
                'web',
                self::WEB_MAX_BYTES,
                self::WEB_MAX_SIDE,
            );
            $thumbnailPath = $this->storeDerivative(
                $thumbnailFiles[$index] ?? null,
                $relativeDirectory.'/thumbnails',
                'thumb',
                self::THUMBNAIL_MAX_BYTES,
                self::THUMBNAIL_MAX_SIDE,
            );

            $originals[$index] = array_filter([
                ...$original,
                ...$metadata,
                'web_path' => $webPath,
                'thumbnail_path' => $thumbnailPath,
                'variant_status' => $webPath !== '' && $thumbnailPath !== '' ? 'ready' : 'pending',
            ], static fn (mixed $value): bool => $value !== null && $value !== '');
        }

        return array_values($originals);
    }

    /** Remove only derivatives created by this service instance during a failed mutation. */
    public function cleanupCreatedDerivatives(): void
    {
        foreach (array_keys($this->createdDerivativePaths) as $relativePath) {
            $absolutePath = $this->absolutePath($relativePath);
            if (is_file($absolutePath)) {
                @unlink($absolutePath);
            }
        }

        $this->createdDerivativePaths = [];
    }

    /** @return array<int, UploadedFile> */
    private function uploadedFiles(mixed $files): array
    {
        if ($files instanceof UploadedFile) {
            return [$files];
        }
        if (! is_array($files)) {
            return [];
        }

        return array_values(array_filter($files, static fn (mixed $file): bool => $file instanceof UploadedFile));
    }

    /** @return array{sha256?: string, size?: int, width?: int, height?: int} */
    private function originalMetadata(string $relativePath): array
    {
        $absolutePath = $this->absolutePath($relativePath);
        if (! is_file($absolutePath)) {
            return [];
        }

        $dimensions = @getimagesize($absolutePath);
        $sha256 = @hash_file('sha256', $absolutePath);
        $size = @filesize($absolutePath);

        return array_filter([
            'sha256' => is_string($sha256) ? $sha256 : null,
            'size' => is_int($size) ? $size : null,
            'width' => is_array($dimensions) ? (int) ($dimensions[0] ?? 0) : null,
            'height' => is_array($dimensions) ? (int) ($dimensions[1] ?? 0) : null,
        ], static fn (mixed $value): bool => $value !== null && $value !== 0 && $value !== '');
    }

    private function storeDerivative(
        ?UploadedFile $file,
        string $relativeDirectory,
        string $prefix,
        int $maxBytes,
        int $maxSide,
    ): string {
        if (! $file instanceof UploadedFile || ! $file->isValid()) {
            return '';
        }

        $size = (int) ($file->getSize() ?: 0);
        $realPath = (string) ($file->getRealPath() ?: '');
        if ($realPath === '' || $size < 1 || $size > $maxBytes) {
            return '';
        }

        $mime = $this->detectMimeType($realPath);
        $extension = self::ALLOWED_MIME_TYPES[$mime] ?? '';
        $dimensions = @getimagesize($realPath);
        $width = is_array($dimensions) ? (int) ($dimensions[0] ?? 0) : 0;
        $height = is_array($dimensions) ? (int) ($dimensions[1] ?? 0) : 0;
        if ($extension === '' || $width < 1 || $height < 1 || max($width, $height) > $maxSide) {
            return '';
        }

        $hash = @hash_file('sha256', $realPath);
        if (! is_string($hash) || $hash === '') {
            return '';
        }

        $relativeDirectory = trim(str_replace('\\', '/', $relativeDirectory), '/');
        $targetDirectory = $this->absolutePath($relativeDirectory);
        if (! is_dir($targetDirectory) && ! mkdir($targetDirectory, 0775, true) && ! is_dir($targetDirectory)) {
            return '';
        }

        $filename = $prefix.'_'.strtolower($hash).'.'.$extension;
        $relativePath = $relativeDirectory.'/'.$filename;
        $targetPath = $targetDirectory.'/'.$filename;
        if (is_file($targetPath)) {
            return $relativePath;
        }

        $temporaryName = '.'.$filename.'.'.bin2hex(random_bytes(6)).'.part';
        $temporaryPath = $targetDirectory.'/'.$temporaryName;
        try {
            $file->move($targetDirectory, $temporaryName);
            if (@link($temporaryPath, $targetPath)) {
                @unlink($temporaryPath);
                $this->createdDerivativePaths[$relativePath] = true;
            } elseif (is_file($targetPath)) {
                @unlink($temporaryPath);
            } elseif (@rename($temporaryPath, $targetPath)) {
                $this->createdDerivativePaths[$relativePath] = true;
            } elseif (is_file($targetPath)) {
                @unlink($temporaryPath);
            } else {
                @unlink($temporaryPath);

                return '';
            }
        } catch (Throwable $exception) {
            if (is_file($temporaryPath)) {
                @unlink($temporaryPath);
            }
            Log::warning('Client image derivative could not be stored.', [
                'field' => $file->getClientOriginalName(),
                'mime_type' => $mime,
                'size' => $size,
                'exception' => $exception,
            ]);

            return '';
        }

        return $relativePath;
    }

    private function absolutePath(string $relativePath): string
    {
        return rtrim((string) config('media.private_root', storage_path('app/private')), '/\\')
            .'/'.trim(str_replace('\\', '/', $relativePath), '/');
    }

    private function sanitizeRelativePath(string $path): string
    {
        $path = trim(str_replace('\\', '/', $path), '/');
        if ($path === '' || str_contains($path, "\0") || preg_match('#(^|/)\.\.(/|$)#', $path) === 1) {
            return '';
        }

        return $path;
    }

    private function detectMimeType(string $path): string
    {
        $finfo = new \finfo(FILEINFO_MIME_TYPE);
        $mime = $finfo->file($path);

        return is_string($mime) ? strtolower(trim($mime)) : '';
    }
}
